import type Database from "better-sqlite3";
import type { CitationDto, ConversationDto, MessageDto } from "../../shared/chat";
type Base={projectId:string;conversationId:string;id:string;content?:string;createdAt:string};
type Assistant=Base&{replyToMessageId:string;provider:string;profileId:string;model:string};
export class ConversationRepository {
 constructor(private readonly db:Database.Database){}
 private own(p:string,c:string){if(!(this.db.prepare("SELECT 1 FROM conversations WHERE id=? AND project_id=? AND deleted_at IS NULL").get(c,p)))throw new Error("conversation not found");}
 private seq(c:string){return (this.db.prepare("SELECT COALESCE(MAX(sequence)+1,0) n FROM messages WHERE conversation_id=?").get(c) as {n:number}).n;}
 createConversation(i:{id:string;projectId:string;title:string;createdAt:string}){this.db.prepare("INSERT INTO conversations VALUES(?,?,?,?,?,NULL)").run(i.id,i.projectId,i.title,i.createdAt,i.createdAt);return this.getConversation(i.projectId,i.id)!;}
 getConversation(p:string,id:string):ConversationDto|undefined{const r=this.db.prepare("SELECT * FROM conversations WHERE id=? AND project_id=?").get(id,p) as any;if(!r) throw new Error("conversation not found");return {id:r.id,projectId:r.project_id,title:r.title,createdAt:r.created_at,updatedAt:r.updated_at,deletedAt:r.deleted_at};}
 listConversations(p:string){return (this.db.prepare("SELECT * FROM conversations WHERE project_id=? AND deleted_at IS NULL ORDER BY updated_at DESC").all(p) as any[]).map(r=>({id:r.id,projectId:r.project_id,title:r.title,createdAt:r.created_at,updatedAt:r.updated_at,deletedAt:r.deleted_at}));}
 appendUserMessage(i:Base){this.own(i.projectId,i.conversationId);const s=this.seq(i.conversationId);this.db.prepare("INSERT INTO messages(id,conversation_id,sequence,role,content,state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(i.id,i.conversationId,s,"user",i.content??"","completed",i.createdAt,i.createdAt);return this.getMessage(i.projectId,i.id)!;}
 startAssistantMessage(i:Assistant){this.own(i.projectId,i.conversationId);const s=this.seq(i.conversationId);this.db.prepare("INSERT INTO messages(id,conversation_id,sequence,role,state,reply_to_message_id,provider,profile_id,model,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(i.id,i.conversationId,s,"assistant","streaming",i.replyToMessageId,i.provider,i.profileId,i.model,i.createdAt,i.createdAt);return this.getMessage(i.projectId,i.id)!;}
 regenerateAssistantMessage(i:Omit<Assistant,"replyToMessageId">&{supersedesMessageId:string}){return this.db.transaction(()=>{const old=this.getMessage(i.projectId,i.supersedesMessageId);if(!old?.replyToMessageId)throw new Error("message not found");this.db.prepare("UPDATE messages SET superseded=1,updated_at=? WHERE id=?").run(i.createdAt,i.supersedesMessageId);const next=this.startAssistantMessage({...i,replyToMessageId:old.replyToMessageId});this.db.prepare("UPDATE messages SET supersedes_message_id=? WHERE id=?").run(i.supersedesMessageId,next.id);return this.getMessage(i.projectId,next.id)!;})();}
 completeAssistantMessage(i:Omit<Base,"createdAt">&{usage:{inputTokens:number;outputTokens:number;totalTokens:number};completionReason?:string;updatedAt:string}){return this.db.transaction(()=>{const m=this.getMessage(i.projectId,i.id);if(m?.role!=="assistant"||m?.state!=="streaming")throw new Error("message not completable");this.db.prepare("UPDATE messages SET content=?,state='completed',usage_json=?,completion_reason=?,updated_at=? WHERE id=?").run(i.content??"",JSON.stringify(i.usage),i.completionReason??"stop",i.updatedAt,i.id);return this.getMessage(i.projectId,i.id)!;})();}
 checkpointAssistantContent(i:{projectId:string;messageId:string;content:string;updatedAt:string}){const m=this.getMessage(i.projectId,i.messageId);if(!m||m.role!=="assistant"||m.state!=="streaming")return;this.db.prepare("UPDATE messages SET content=?,updated_at=? WHERE id=? AND state='streaming'").run(i.content,i.updatedAt,i.messageId);}
 cancelAssistantMessage(i:{projectId:string;messageId:string;updatedAt:string}){const m=this.getMessage(i.projectId,i.messageId);if(!m||m.role!=="assistant"||m.state!=="streaming")throw new Error("message not cancellable");this.db.prepare("UPDATE messages SET state='cancelled',completion_reason=COALESCE(completion_reason,'user_abort'),updated_at=? WHERE id=?").run(i.updatedAt,i.messageId);return this.getMessage(i.projectId,i.messageId)!;}
 failAssistantMessage(i:{projectId:string;messageId:string;errorCode:string;updatedAt:string}){const m=this.getMessage(i.projectId,i.messageId);if(!m||m.role!=="assistant"||m.state!=="streaming")throw new Error("message not failable");this.db.prepare("UPDATE messages SET state='failed',error_code=?,updated_at=? WHERE id=?").run(i.errorCode,i.updatedAt,i.messageId);return this.getMessage(i.projectId,i.messageId)!;}
 addCitation(i:{projectId:string;messageId:string;id:string;label:string;sourceId:string;sourceChunkId:string;sourceDisplayName:string;sourceKind:string;locator:unknown;quote?:string;createdAt:string;start?:number}){return this.db.transaction(()=>{const m=this.getMessage(i.projectId,i.messageId);if(!m)throw new Error("message not found");this.own(i.projectId,m.conversationId);this.db.prepare("INSERT INTO message_citations(id,message_id,label,source_id,source_chunk_id,source_display_name,source_kind,locator_json,quote,created_at,start) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(i.id,i.messageId,i.label,i.sourceId,i.sourceChunkId,i.sourceDisplayName,i.sourceKind,JSON.stringify(i.locator),i.quote??null,i.createdAt,i.start??0);return this.getMessage(i.projectId,i.messageId)!.citations.find(c=>c.id===i.id)!;})();}
 removeConversation(p:string,id:string,d:string){this.own(p,id);this.db.prepare("UPDATE conversations SET deleted_at=?,updated_at=? WHERE id=?").run(d,d,id);}
 getMessage(p:string,id:string):MessageDto|undefined{const r=this.db.prepare("SELECT m.* FROM messages m JOIN conversations c ON c.id=m.conversation_id WHERE m.id=? AND c.project_id=?").get(id,p) as any;if(!r)return;const cs=(this.db.prepare("SELECT * FROM message_citations WHERE message_id=?").all(id) as any[]).map(c=>({id:c.id,label:c.label,sourceId:c.source_id,sourceChunkId:c.source_chunk_id,sourceDisplayName:c.source_display_name,sourceKind:c.source_kind,locator:JSON.parse(c.locator_json),quote:c.quote??undefined}));return {id:r.id,conversationId:r.conversation_id,sequence:r.sequence,role:r.role,content:r.content,state:r.state,replyToMessageId:r.reply_to_message_id,supersedesMessageId:r.supersedes_message_id??null,superseded:Boolean(r.superseded),provider:r.provider??null,profileId:r.profile_id??null,model:r.model??null,usage:r.usage_json?JSON.parse(r.usage_json):null,errorCode:r.error_code??null,completionReason:r.completion_reason??null,createdAt:r.created_at,updatedAt:r.updated_at,citations:cs};}
 listMessages(p:string,c:string){this.own(p,c);return (this.db.prepare("SELECT id FROM messages WHERE conversation_id=? ORDER BY sequence").pluck().all(c) as string[]).map(id=>this.getMessage(p,id)!);}
}
