import { z } from "zod";

export const embeddingFingerprintSchema = z.object({ provider: z.string().min(1), modelId: z.string().min(1), modelRevision: z.string().min(1), dimension: z.number().int().positive(), distance: z.literal("cosine"), pooling: z.literal("mean"), preprocessVersion: z.string().min(1), chunkingVersion: z.string().min(1) });
export const embeddingSpaceSchema = z.object({ id: z.uuid(), projectId: z.uuid(), fingerprint: z.string().min(1), state: z.enum(["preparing", "building", "validating", "active", "failed", "retired"]), progress: z.number().int().min(0).max(1000), fingerprintData: embeddingFingerprintSchema });
export const vectorHealthSchema = z.object({ spaceId: z.uuid(), healthy: z.boolean(), indexedCount: z.number().int().nonnegative() });
export const searchHitSchema = z.object({ chunkId: z.string().min(1), score: z.number().finite(), text: z.string(), locator: z.unknown() });
export const vectorTaskInputSchema = z.object({ projectId: z.uuid() }).strict();
export const vectorSpaceInputSchema = vectorTaskInputSchema.extend({ spaceId: z.uuid() }).strict();
export const vectorProfileInputSchema = vectorTaskInputSchema.extend({ profileId: z.uuid() }).strict();
export const vectorTaskIdInputSchema = vectorTaskInputSchema.extend({ taskId: z.uuid() }).strict();
export const retrievalSearchInputSchema = vectorTaskInputSchema.extend({ query: z.string().trim().min(1).max(20_000), limit: z.number().int().min(1).max(100).default(12) }).strict();
export type VectorTaskInput = z.infer<typeof vectorTaskInputSchema>;
export type VectorSpaceInput = z.infer<typeof vectorSpaceInputSchema>;
export type VectorProfileInput = z.infer<typeof vectorProfileInputSchema>;
export type VectorTaskIdInput = z.infer<typeof vectorTaskIdInputSchema>;
export type RetrievalSearchInput = z.infer<typeof retrievalSearchInputSchema>;
export type EmbeddingFingerprint = Readonly<z.infer<typeof embeddingFingerprintSchema>>;
export type EmbeddingSpaceDto = Readonly<z.infer<typeof embeddingSpaceSchema>>;
export type VectorHealthDto = Readonly<z.infer<typeof vectorHealthSchema>>;
export type SearchHitDto = Readonly<z.infer<typeof searchHitSchema>>;
