import React, { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { transformationPromptSchema, type TransformationAppliesTo, type TransformationDto } from "../../../shared/transformations";

export default function RuleEditorDialog({ rule, onCancel, onSave }: Readonly<{ rule?: TransformationDto | undefined; onCancel(): void; onSave(value: { name: string; appliesTo: TransformationAppliesTo; prompt: string; id?: string; version?: number; enabled?: boolean }): Promise<void> }>) {
  const { t } = useTranslation(); const [name, setName] = useState(rule?.name ?? ""); const [appliesTo, setAppliesTo] = useState<TransformationAppliesTo>(rule?.appliesTo ?? "source"); const [prompt, setPrompt] = useState(rule?.prompt ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { document.getElementById("rule-name")?.focus(); }, []);
  function validate(): string { const result = transformationPromptSchema.safeParse(prompt); return result.success ? "" : (result.error.issues[0]?.message ?? t("transformations.invalidPrompt", "Use only the four supported placeholders.")); }
  async function submit(event: React.FormEvent): Promise<void> { event.preventDefault(); const promptError = validate(); if (!name.trim() || promptError) { setError(promptError || t("transformations.ruleNameRequired", "Enter a rule name.")); return; } setBusy(true); setError(""); try { await onSave({ name, appliesTo, prompt, ...(rule ? { id: rule.id, version: rule.version, enabled: rule.enabled } : {}) }); } catch (cause) { setError(cause instanceof Error ? cause.message : t("errors.internal", "Unable to save rule.")); setBusy(false); } }
  const promptError = prompt ? validate() : "";
  return <div className="dialog-layer" onMouseDown={(e) => { if (e.target === e.currentTarget && !busy) onCancel(); }}><section className="dialog-card rule-dialog" role="dialog" aria-modal="true" aria-labelledby="rule-dialog-title"><form onSubmit={(e) => void submit(e)}><h2 id="rule-dialog-title">{rule ? t("transformations.editRule", "Edit custom rule") : t("transformations.newRule", "New custom rule")}</h2><label htmlFor="rule-name">{t("transformations.ruleName", "Rule name")}</label><input id="rule-name" value={name} onChange={(e) => setName(e.target.value)} maxLength={100} /><label htmlFor="rule-target">{t("transformations.appliesTo", "Applies to")}</label><select id="rule-target" value={appliesTo} onChange={(e) => setAppliesTo(e.target.value as TransformationAppliesTo)}>{["source", "sources", "message", "answer", "note"].map((item) => <option key={item} value={item}>{item}</option>)}</select><label htmlFor="rule-prompt">{t("transformations.prompt", "Prompt")}</label><textarea id="rule-prompt" value={prompt} onChange={(e) => setPrompt(e.target.value)} aria-describedby="rule-placeholders rule-error" /> <p id="rule-placeholders" className="field-help">{t("transformations.placeholders", "Allowed placeholders")}: {"{{content}}"}, {"{{source_title}}"}, {"{{project_name}}"}, {"{{language}}"}. {t("transformations.placeholderHelp", "HTML and other template syntax are rejected.")}</p>{(error || promptError) && <p id="rule-error" className="inline-error" role="alert">{error || promptError}</p>}<div className="dialog-actions"><button type="button" disabled={busy} onClick={onCancel}>{t("common.cancel", "Cancel")}</button><button className="primary-button" type="submit" disabled={busy || Boolean(promptError)}>{busy ? t("common.saving", "Saving…") : t("common.save", "Save")}</button></div></form></section></div>;
}
