import React, { useEffect, useMemo, useRef, useState } from "react";
import type { Result } from "../../../shared/app-errors";
import type { SourceDto } from "../../../shared/sources";
import type { TaskDto } from "../../../shared/tasks";
import ImportDialog from "./ImportDialog";
import TaskProgress, { type TaskProgressLabels } from "../tasks/TaskProgress";

type SourcesApi = { chooseFiles: (input: { projectId: string }) => Promise<string[] | null>; importFile: (input: { projectId: string; dialogToken: string }) => Promise<Result<SourceDto>>; importUrl: (input: { projectId: string; url: string }) => Promise<Result<SourceDto>>; list: (input: { projectId: string }) => Promise<SourceDto[]>; remove: (input: { projectId: string; sourceId: string }) => Promise<Result<void>>; retry: (input: { projectId: string; sourceId: string }) => Promise<Result<TaskDto>> };
type TasksApi = { list: (input: { projectId: string }) => Promise<TaskDto[]>; cancel: (input: { projectId: string; taskId: string }) => Promise<Result<TaskDto>>; subscribe?: (projectId: string, listener: (task: TaskDto) => void) => () => void };
type Labels = Partial<TaskProgressLabels> & { title: string; importTitle?: string; add: string; empty: string; remove: string; selected: string; file: string; url: string; webAddress?: string; formats?: string; importing?: string; error?: string; errorMessages?: Record<string, string>; indexed?: string; pending?: string; openSettings?: string; importLabel?: string; importCancel?: string };

export default function SourcePanel({ projectId, sourcesApi, tasksApi, labels, importOpen, onImportOpen, onImportClose, onOpenSettings, onImported, importTriggerRef }: { projectId: string; sourcesApi: SourcesApi; tasksApi: TasksApi; labels: Labels; importOpen?: boolean; onImportOpen?: () => void; onImportClose?: () => void; onOpenSettings?: () => void; onImported?: () => void; importTriggerRef?: React.RefObject<HTMLElement | null> }) {
  const { remove: _remove, errorMessages, ...taskOverrides } = labels;
  const taskLabels: TaskProgressLabels = { cancel: "Cancel", retry: "Retry", remove: "Remove", completed: "Completed", failed: "Failed", queued: "Queued", running: "Running", cancelled: "Cancelled", validating: "Validating", staging: "Staging", parsing: "Parsing", chunking: "Chunking", embedding: "Embedding", indexing: "Indexing", verifying: "Verifying", cleanup: "Cleaning up", finalizing: "Finalizing", preparing: "Preparing", generating: "Generating", saving: "Saving", ...taskOverrides };
  const [sources, setSources] = useState<SourceDto[]>([]); const [tasks, setTasks] = useState<TaskDto[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const addButtonRef = useRef<HTMLButtonElement>(null); const lastTriggerRef = useRef<HTMLElement | null>(null);
  const dialogOpen = importOpen ?? open;
  useEffect(() => { if (dialogOpen && !lastTriggerRef.current && importTriggerRef?.current) lastTriggerRef.current = importTriggerRef.current; }, [dialogOpen, importTriggerRef]);
  const refresh = async () => { try { const [nextSources, nextTasks] = await Promise.all([sourcesApi.list({ projectId }), tasksApi.list({ projectId })]); setSources(nextSources); setTasks(nextTasks); } catch { setError("errors.internal"); } };
  useEffect(() => { setSelectedId(undefined); void refresh(); const unsubscribe = tasksApi.subscribe?.(projectId, (task) => setTasks((current) => [task, ...current.filter((item) => item.id !== task.id)].sort((a, b) => b.createdAt.localeCompare(a.createdAt)))); return unsubscribe; }, [projectId]);
  const taskBySource = useMemo(() => { const next = new Map<string, TaskDto>(); for (const task of tasks) if (task.sourceId && !next.has(task.sourceId)) next.set(task.sourceId, task); return next; }, [tasks]);
  async function remove(sourceId: string): Promise<void> { const result = await sourcesApi.remove({ projectId, sourceId }); if (!result.ok) { setError(result.error.messageKey); return; } setSources((current) => current.filter((source) => source.id !== sourceId)); }
  async function retry(sourceId: string): Promise<void> { const result = await sourcesApi.retry({ projectId, sourceId }); if (!result.ok) setError(result.error.messageKey); else setTasks((current) => [result.value, ...current.filter((task) => task.sourceId !== sourceId)]); }
  async function cancel(taskId: string): Promise<void> { const result = await tasksApi.cancel({ projectId, taskId }); if (!result.ok) setError(result.error.messageKey); else setTasks((current) => current.map((task) => task.id === taskId ? result.value : task)); }
  const closeDialog = () => { setOpen(false); onImportClose?.(); const trigger = lastTriggerRef.current ?? addButtonRef.current; queueMicrotask(() => { trigger?.focus(); lastTriggerRef.current = null; }); };
  const openDialog = () => { lastTriggerRef.current = addButtonRef.current; if (onImportOpen) onImportOpen(); else setOpen(true); };
  return <aside className="sources-panel" aria-label={labels.title}><header><h3>{labels.title}</h3><button ref={addButtonRef} type="button" aria-label={labels.add} onClick={openDialog}>＋</button></header>
    {error && <p className="inline-error" role="alert">{errorMessages?.[error] ?? error}</p>}
    <div className="source-list">{sources.length === 0 ? <div className="sources-empty"><span aria-hidden="true">□＋</span><strong>{labels.empty}</strong></div> : sources.map((source) => { const task = taskBySource.get(source.id); const selected = selectedId === source.id; const indexed = source.currentRevisionId && source.currentRevisionState === "ready"; return <div className={`source-row${selected ? " selected" : ""}`} key={source.id}><button type="button" className="source-select" aria-pressed={selected} aria-label={`${selected ? labels.selected + ": " : ""}${source.displayName}`} onClick={() => setSelectedId(selected ? undefined : source.id)}><strong>{source.displayName}</strong><small>{source.locator ?? source.displayName} · {source.kind} · {indexed ? (labels.indexed ?? labels.pending) : labels.pending}</small></button><button type="button" onClick={() => void remove(source.id)}>{labels.remove}</button>{task && <TaskProgress task={task} labels={taskLabels} {...(errorMessages ? { errorMessages } : {})} onCancel={() => void cancel(task.id)} onRetry={() => void retry(source.id)} onDelete={() => void remove(source.id)} onOpenSettings={onOpenSettings} />}</div>; })}</div>
    <ImportDialog projectId={projectId} open={dialogOpen} chooseFiles={sourcesApi.chooseFiles} importFile={sourcesApi.importFile} importUrl={sourcesApi.importUrl} onClose={closeDialog} onImported={() => { void refresh(); onImported?.(); }} labels={{ title: labels.importTitle ?? labels.add, file: labels.file, url: labels.url, ...(labels.webAddress ? { urlLabel: labels.webAddress } : {}), ...(labels.formats ? { formats: labels.formats } : {}), ...(labels.importing ? { importing: labels.importing } : {}), ...(labels.error ? { error: labels.error } : {}), ...(labels.importCancel ?? labels.cancel ? { cancel: labels.importCancel ?? labels.cancel } : {}), ...(labels.importLabel ? { import: labels.importLabel } : {}) }} />
  </aside>;
}
