import { SpaceRepository } from "./space-repository";
import type { SpaceSpec } from "./space-repository";
type SpaceOps = { rebuild(input:unknown):Promise<void>; optimize(input:unknown):Promise<void> };
type Backup = () => Promise<unknown>;
export class SpaceService {
  private readonly controllers = new Map<string, AbortController>();
  constructor(private repo:SpaceRepository, private ops?:SpaceOps, private backup?:Backup) {}
  async recoverInterrupted():Promise<void> { await this.repo.recoverInterrupted(); }
  async rebuild(input:unknown):Promise<void> { if (!this.ops) throw new Error("rebuild is not configured"); const request=input as { taskId?:string; spec:SpaceSpec; verify?:()=>Promise<void>; signal?:AbortSignal }; const controller=new AbortController(); const signal=request.signal ? AbortSignal.any([request.signal, controller.signal]) : controller.signal; if (request.taskId) this.controllers.set(request.taskId, controller); const space=this.repo.createOrReuse(request.spec); try { if (signal.aborted) throw Object.assign(new Error("Space build cancelled"), { code:"SPACE_BUILD_CANCELLED" }); this.repo.setState?.(space.id,"building"); await this.ops.rebuild({ ...request, signal, authoritative: "sqlite", space }); if (signal.aborted) throw Object.assign(new Error("Space build cancelled"), { code:"SPACE_BUILD_CANCELLED" }); this.repo.setState?.(space.id,"validating",1000); if(request.verify) await request.verify(); if(this.backup) await this.backup(); this.repo.activate(request.spec.projectId, space.id); } catch(error) { if((error as any)?.code === "SPACE_BUILD_CANCELLED" || signal.aborted) { await this.repo.cancel(space.id); throw Object.assign(error instanceof Error ? error : new Error("Space build cancelled"), { code:"SPACE_BUILD_CANCELLED" }); } try { await this.repo.fail(space.id); } catch (cleanup) { throw new AggregateError([error, cleanup], "Space build failed and cleanup failed"); } throw error; } finally { if (request.taskId && this.controllers.get(request.taskId)===controller) this.controllers.delete(request.taskId); } }
  async optimize(input:unknown):Promise<void> { if (!this.ops) throw new Error("optimize is not configured"); const request=input as { taskId?:string; signal?:AbortSignal }; const controller=new AbortController(); const signal=request.signal ? AbortSignal.any([request.signal, controller.signal]) : controller.signal; if (request.taskId) this.controllers.set(request.taskId, controller); try { if (signal.aborted) throw Object.assign(new Error("Optimize cancelled"),{code:"TASK_CANCELLED"}); await this.ops.optimize({ ...request, signal }); if (signal.aborted) throw Object.assign(new Error("Optimize cancelled"),{code:"TASK_CANCELLED"}); } finally { if (request.taskId && this.controllers.get(request.taskId)===controller) this.controllers.delete(request.taskId); } }
  cancel(taskId:string):boolean { const controller=this.controllers.get(taskId); if (!controller) return false; controller.abort(); return true; }
  async build(spec:SpaceSpec, work:()=>Promise<void>, signal?:AbortSignal):Promise<void> { const space=this.repo.createOrReuse(spec); try { if(signal?.aborted) throw Object.assign(new Error("Space build cancelled"), { code:"SPACE_BUILD_CANCELLED" }); await work(); if(signal?.aborted) throw Object.assign(new Error("Space build cancelled"), { code:"SPACE_BUILD_CANCELLED" }); if(this.backup) await this.backup(); this.repo.activate(spec.projectId,space.id); } catch(error) { if((error as any)?.code==="SPACE_BUILD_CANCELLED") await this.repo.cancel(space.id); else { try { await this.repo.fail(space.id); } catch (cleanup) { throw new AggregateError([error, cleanup], "Space build failed and cleanup failed"); } } throw error; } }
}
